/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package typeid;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Stream;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

class TypeIDTest {
  private static final ObjectMapper MAPPER = new ObjectMapper(new YAMLFactory());

  record Valid(String name, String prefix, String typeid, String uuid) {}

  record Invalid(String name, String typeid, String description) {}

  @ParameterizedTest
  @MethodSource("validParams")
  void valid(Valid valid) {
    var typeId = TypeID.fromString(valid.typeid()).get();
    assertEquals(valid.prefix(), typeId.prefix(), valid.name());
    assertEquals(valid.uuid(), typeId.uuid().toString());
  }

  @ParameterizedTest
  @MethodSource("invalidParams")
  void invalid(Invalid invalid) {
    assertEquals(Optional.empty(), TypeID.fromString(invalid.typeid()), invalid.description());
  }

  @Test
  void twoWay() {
    var in = new TypeID("test");
    assertEquals(Optional.of(in), TypeID.fromString(in.toString()));
  }

  @Test
  void fromUUID() {
    var uuid = UUID.fromString("3c098018-c8b3-44f3-98b0-3bfaca73ec48");
    assertEquals(
        Optional.of("prefix_1w1601hj5k8ksshc1vzb577v28"),
        TypeID.fromUUID("prefix", uuid).map(Objects::toString));
  }

  static Stream<Valid> validParams() throws IOException {
    return MAPPER
        .readValue(
            TypeIDTest.class.getResourceAsStream("/valid.yml"), new TypeReference<List<Valid>>() {})
        .stream();
  }

  static Stream<Invalid> invalidParams() throws IOException {
    return MAPPER
        .readValue(
            TypeIDTest.class.getResourceAsStream("/invalid.yml"),
            new TypeReference<List<Invalid>>() {})
        .stream();
  }
}
